In [1]:
import numpy as np

In [15]:
A = np.array([[1, -1, 0.1, 2, -2, -.2]]).reshape(2,3)
At = A.T
# Columns of A are a1, a2, and a3
# Rows of At are a1, a2, and a3

W = np.array([3,5,7,9,4,6,8,0]).reshape(2,-1)

# Columns of W are w1, w2, w3, and w4


Z = At @ W 

# The following are all equivalent:
Z_matmul = np.matmul(At,W)
Z_matmul2 = np.matmul(A.T,W)
Z_address = At @ W
Z_address2 = A.T @ W

In [20]:
display(At,W)
print()
display(Z, Z_matmul, Z_matmul2, Z_address, Z_address2)

array([[ 1. ,  2. ],
       [-1. , -2. ],
       [ 0.1, -0.2]])

array([[3, 5, 7, 9],
       [4, 6, 8, 0]])

array([[ 11. ,  17. ,  23. ,   9. ],
       [-11. , -17. , -23. ,  -9. ],
       [ -0.5,  -0.7,  -0.9,   0.9]])

array([[ 11. ,  17. ,  23. ,   9. ],
       [-11. , -17. , -23. ,  -9. ],
       [ -0.5,  -0.7,  -0.9,   0.9]])

array([[ 11. ,  17. ,  23. ,   9. ],
       [-11. , -17. , -23. ,  -9. ],
       [ -0.5,  -0.7,  -0.9,   0.9]])

array([[ 11. ,  17. ,  23. ,   9. ],
       [-11. , -17. , -23. ,  -9. ],
       [ -0.5,  -0.7,  -0.9,   0.9]])

array([[ 11. ,  17. ,  23. ,   9. ],
       [-11. , -17. , -23. ,  -9. ],
       [ -0.5,  -0.7,  -0.9,   0.9]])