In [60]:
import numpy as np

## Dense Layer Vectorized

In [86]:
def sigmoid(Z):
    ret = 1/(1+ np.exp(-Z))
    return ret

In [68]:
# Input feature values 200 and 17
At = np.array([200, 17]) # 200 degrees at 17 minutes
At = At.reshape(1,2)
m, n = At.shape
print(f'Matrix A_transpose is of shape ({m}x{n})')

Matrix A_transpose is of shape (1x2)


### Define $W$ and $b$

Recall:

$\mathbf{W}$ should be of size (# input features, # elements in layer). So the number of input features is 2, and the number of elements (from the network defined in the lab) is 3. Thus, $\mathbf{W}$ should be $\left(2\times3\right)$. In other words,

$\mathbf{W} = \begin{bmatrix} w_{11} & w_{12} & w_{13}
                            \\ w_{21} & w_{22} & w_{23} \end{bmatrix}$

$\mathbf{B}$ should be the same size as the number of elements in the layer. Since there are three elements in the first layer, the size of b should be $(1\times3)$, or in other words,

$\mathbf{B} = \begin{bmatrix} b_1 & b_2 & b_3 \end{bmatrix}$

### Calculate Z 

Know that the equivalent of `np.dot(w,a)` in matrix form is $A^{T}W$ when for $A$ the rows are $\vec{a_1}$ and $\vec{a_2}$, etc. and the columns of $\mathbf{W}$ are the vectors $\vec{w_1}$, $\vec{w_2}$, etc.

Thus, $Z=A^TW + B$ is equivalent to taking the individual dot products `z = np.dot(w,a) + b` for all weight vectors $w_1 ... w_n$ and inputs $a_1 .. a_n$. 

In [111]:
W = np.array([[1, -3, 5],[-2, 4, -6]]); B = np.array([-1,1,2])

In [131]:
Z = At @ W + B

### Calculate Activation

In [123]:
predictions = sigmoid(Z)
yhat = (predictions >= 0.5).astype(int)
display(predictions, yhat)

array([[1.00000000e+000, 2.45261912e-231, 1.00000000e+000]])

array([[1, 0, 1]])

In [126]:
def dense(AT, W, B):
    Z = AT @ W + B
    af = lambda Z: 1/(1+np.exp(-Z))
    A_out = af(Z)
    return A_out

In [130]:
# If dense layer is the output layer, then apply the threshold for logistic regression and get a yhat value
yhat = (dense(At,W,B) >= 0.5).astype(int)
yhat

array([[1, 0, 1]])